# Exclude database files from secret scanning
# The nodes.db contains workflow templates with placeholder API keys that trigger false positives
paths-ignore:
  - "data/nodes.db"
  - "data/*.db"
  - "nodes.db"